const { Neo4jGraphQL } = require("@neo4j/graphql");
const { OGM } = require("@neo4j/graphql-ogm");
const { ApolloServer } = require("apollo-server");
const neo4j = require("neo4j-driver");
const fs = require("fs");
const dotenv = require("dotenv");
const path = require("path");
var nJwt = require("njwt");

// Load contents of .env as environment variables
dotenv.config();

// Load GraphQL type definitions from schema.graphql file
const typeDefs = fs
  .readFileSync(path.join(__dirname, "todo.graphql"))
  .toString("utf-8");

// Create Neo4j driver instance
const driver = neo4j.driver(
  "bolt://localhost:7687",
  neo4j.auth.basic("neo4j", "rootroot")
);

const ogm = new OGM({ typeDefs, driver });
const User = ogm.model("User");

const resolvers = {
    Mutation: {
        signUp: async (_source, { username, password }) => {
            const [existing] = await User.find({
                where: {
                    username,
                },
            });

	    console.log("existing", existing);

            if (existing) {
                throw new Error(`User with username ${username} already exists!`);
            }

	    const roles = ["user"];
            const user = await User.create({
                input: [
                    {
                        username,
                        password,
			roles
                    }
                ]
            });
	    
            return nJwt.create({ sub: user.users[0].id, roles: user.users[0].roles }, signingKey).setExpiration().compact();
        },
        signIn: async (_source, { username, password }) => {
            const [user] = await User.find({
                where: {
                    username,
                },
            });

            if (!user) {
                throw new Error(`User with username ${username} not found!`);
            }

            const correctPassword = password == user.password;

            if (!correctPassword) {
                throw new Error(`Incorrect password for user with username ${username}!`);
            }

            return nJwt.create({ sub: user.id, roles: user.roles }, signingKey).setExpiration().compact();
        },
    },
};

// Create executable GraphQL schema from GraphQL type definitions,
// using @neo4j/graphql to autogenerate resolvers
const neoSchema = new Neo4jGraphQL({
    typeDefs,
    resolvers,
    config: {
	jwt: {
	    secret: "dFt8QaYykR6PauvxcyKVXKauxvQuWQTc"
	}
    }
});
var signingKey = "dFt8QaYykR6PauvxcyKVXKauxvQuWQTc";

// Create ApolloServer instance that will serve GraphQL schema created above
// Inject Neo4j driver instance into the context object, which will be passed
//  into each (autogenerated) resolver
const server = new ApolloServer({
  context:({req}) => ({ driver, req }),
  schema: neoSchema.schema,
  //introspection: true,
//  playground: false
});

// Start ApolloServer
server.listen().then(({ url }) => {
  console.log(`GraphQL server ready at ${url}`);
});
